### ISSUE TITLE
Import resource repository throws odd error.

### ISSUE THREAD

**Issue by JFolberth** [samsmithnz/AzurePipelinesToGitHubActionsConverter#227]
**Describe the bug**
When running a YAML pipeline that references another repository the error message is:
Resource repositories conversion not yet done: https://github.com/samsmithnz/AzurePipelinesToGitHubActionsConverter/issues/8

That issue is closed and not sure if it accurately lines up.    This is the expanded output of a YAML pipeline that leverages a shared template repository.  The steps all expanded but kept the reference to the repo.  

**Expected behavior**
Given the setup I'd expect it to display a different error message since I would assume the converter wouldn't know about my other repo.

**Screenshots**
#TODO: Resource repositories conversion not yet done: https://github.com/samsmithnz/AzurePipelinesToGitHubActionsConverter/issues/8
#

**Additional context**
Worked pretty well!

**Comment by samsmithnz** [comment]
Thanks @JFolberth. Do you have sample YAML you could share to expediate this? As a bonus what you expect it to look like in Actions would be extremely helpful too. I admit I haven't spent a lot of time in this section, except that initially the Actions support for repositories was very limited.

**Comment by JFolberth** [comment]
Sure!

Here is what the YAML looks like.  In this scenario the YAML is in the same ADO Project:
```
resources:
  repositories:
  - repository: YAMLTemplates
    type: git
    name: YAMLTemplates/YAMLTemplates
```

I'm not sure what it would look like in Actions as I haven't played around too much.  Given the setup of your project I don't believe this is a huge concern as your site won't know about the repository unless it's setup with a connection to it.  I think it's more so just the TODO message doesn't make sense in this scenario.
