### ISSUE TITLE
consumers of the nuget unable to debug

### ISSUE THREAD

**Issue by f2calv** [samsmithnz/AzurePipelinesToGitHubActionsConverter#297]
So I was upgrading [yamlizr](https://github.com/f2calv/yamlizr) to consume the newest version of your package but I ran into some issues. Basically errors are being thrown inside your library however I am unable to debug them (easily) because your CI doesn't publish a NuGet package with the debugging symbols available via [SourceLink](https://github.com/dotnet/sourcelink). See red crosses below...

![image](https://user-images.githubusercontent.com/16097639/119025191-2ca94d00-b9a4-11eb-9157-6a5ea00d25a6.png)

Whereas the result should look like;

![image](https://user-images.githubusercontent.com/16097639/119025617-9a557900-b9a4-11eb-9bfd-97cdc6a6d938.png)

Note: the last red tick will turn green when the built nuget originates on github/azdo.

PR incoming...

**Comment by f2calv** [comment]
Note: there is a (very new) one-stop nuget package which handles a lot of the nuget symbols/debug stuff, however I believe this PR is a good first step to learn the whys & hows and you can refactor later to use https://github.com/dotnet/reproducible-builds

**Comment by f2calv** [comment]
@samsmithnz re-pushed the branch with fixes;
- no dotnet restore step
- package path globbing correct

**Comment by samsmithnz** [comment]
@f2calv: I had to restore the nuget step, a bunch of stuff was broken, and I don't have time to debug today. Looks like it's working now. I think it's good to have a separate step anyway - to ensure both the windows and linux build work - before pushing to nuget.

**Comment by f2calv** [comment]
So it's not working right, v0.18.2 now looks correct as far as nuget package explorer is concerned;
![image](https://user-images.githubusercontent.com/16097639/120734941-03cba080-c4ea-11eb-8c92-96a16212f4b4.png)

However when I debug I am unable to load the symbols and step into the code;
![image](https://user-images.githubusercontent.com/16097639/120734718-a6375400-c4e9-11eb-9b72-01a288a249f1.png)

The [latest build artifact](https://github.com/samsmithnz/AzurePipelinesToGitHubActionsConverter/suites/2863536670/artifacts/63966990) contains the right files;
![image](https://user-images.githubusercontent.com/16097639/120735072-39708980-c4ea-11eb-81b8-4eabf8c94515.png)

But the nuget page doesn't show the snupkg available for download;
![image](https://user-images.githubusercontent.com/16097639/120735470-f5ca4f80-c4ea-11eb-8042-5544f94ca37d.png)

Which is understandable as the NuGetPush job doesn't push the snupkg packages;
![image](https://user-images.githubusercontent.com/16097639/120735116-4e4d1d00-c4ea-11eb-960a-53ff1e542ad7.png)

Like it should in [my workflow](https://github.com/f2calv/CasCap.Apis.GooglePhotos/runs/2719995947?check_suite_focus=true);
![image](https://user-images.githubusercontent.com/16097639/120735385-d0d5dc80-c4ea-11eb-9ccd-eff92c674d0b.png)

What is different here?

My push command line;
`dotnet nuget push ${{ github.workspace }}/src/**/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json`

Your push command line;
`dotnet nuget push nugetPackage\*.nupkg --api-key "${{ secrets.GHPackagesToken }}" --source "https://www.nuget.org/"`

...fundamentally both lines are identical.

**Comment by samsmithnz** [comment]
I can look first thing in the am. If you make a PR while I sleep, please consider only changing one thing- the last pr was too complex with a few issues hiding.

**Comment by f2calv** [comment]
Ok cool.

I think it can only be that the your source endpoint is not specifying a version, according to https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/ it should be the one I am using - which specifies `https://api.nuget.org/v3/index.json`

Note: what I also don't get, is that source link itself should just allow debugging (grabbing the code from the remote git repo) and not even need the symbol file to be pushed or at least that was my understanding.

**Comment by samsmithnz** [comment]
Reopening until issue is confirmed

**Comment by samsmithnz** [comment]
@f2calv  I received an extra email this time - I didn't get this in the last release. Perhaps it's good now?

![image](https://user-images.githubusercontent.com/8389039/120798176-f70b7480-c50a-11eb-904f-8018c40e2073.png)

**Comment by f2calv** [comment]
Yep 0.18.3 now has symbols :)

![image](https://user-images.githubusercontent.com/16097639/120827310-9a847580-c55b-11eb-8a63-ac85d5174e26.png)
