### ISSUE TITLE
[Security] Workflow CI.yml is using vulnerable action gittools/actions/gitversion/execute

### ISSUE THREAD

**Issue by Ale0x78** [samsmithnz/AzurePipelinesToGitHubActionsConverter#330]
The workflow CI.yml is referencing action gittools/actions/gitversion/execute using references v0.9.7. However this reference is missing the commit [90150b40fdd6c4b06d39cfd764e900cff45ccfca](https://github.com/gittools/actions/commits/90150b40fdd6c4b06d39cfd764e900cff45ccfca) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by samsmithnz** [comment]
Thanks for letting me know, and sorry for the delay - I didn't see this as I turned off notifications where I wasn't tagged. Pushing a fix in the next 24 hours!
