### ISSUE TITLE
Some Azuredevops tasks properly not converted into github workflows

### ISSUE THREAD

**Issue by sesa740202** [samsmithnz/AzurePipelinesToGitHubActionsConverter#449]
getting below error
#Error (line 27): the step 'synopsys-coverity.synopsys-coverity-azure-devops.coverity-task.synopsys-coverity@1' does not have a conversion path yet
#Error (line 47): the step 'UniversalPackages@0' does not have a conversion path yet
#Error (line 62): the step 'benjhuser.tfs-extensions-build-tasks.trigger-build-task.TriggerBuild@3' does not have a conversion path yet
#Error (line 65): the step 'benjhuser.tfs-extensions-build-tasks.trigger-build-task.TriggerBuild@3' does not have a conversion path yet
#Error (line 88): the step 'mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3' does not have a conversion path yet

detailed steps:
 # "Error: the step 'synopsys-coverity.synopsys-coverity-azure-devops.coverity-task.synopsys-coverity@1' does not have a conversion path yet"
      name: Synopsys Coverity "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe" ${{ github.workspace }}\Source\Framework.Dependencies.sln /p:Configuration="Release" /p:Platform="Any CPU" /m /p:FileVersionString=${{ github.run_number }}
      run: |
        echo "Error: the step 'synopsys-coverity.synopsys-coverity-azure-devops.coverity-task.synopsys-coverity@1' does not have a conversion path yet"
        #task: synopsys-coverity.synopsys-coverity-azure-devops.coverity-task.synopsys-coverity@1
        #displayName: Synopsys Coverity "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe" ${{ github.workspace }}\Source\Framework.Dependencies.sln /p:Configuration="Release" /p:Platform="Any CPU" /m /p:FileVersionString=${{ github.run_number }}
        #continueOnError: true
        #inputs:
        #  coverityservice: f88331a5-5764-445b-897c-cd5d6bac3b4e
        #  projectname: Ecostruxure Power Monitoring Expert
        #  streamname: ${{ env.Build.DefinitionName }}
        #  checkissues: true
        #  issueview: High Impact Outstanding
        #  buildcommand: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe" ${{ github.workspace }}\Source\Framework.Dependencies.sln /p:Configuration="Release" /p:Platform="Any CPU" /m /p:FileVersionString=${{ github.run_number }}'
        #  allowuntrusted: true

 - # "Error: the step 'UniversalPackages@0' does not have a conversion path yet"
      name: Publish se.framework.dependencies.runtime Package
      run: |
        echo "Error: the step 'UniversalPackages@0' does not have a conversion path yet"
        #task: UniversalPackages@0
        #displayName: Publish se.framework.dependencies.runtime Package
        #inputs:
        #  command: publish
        #  publishdirectory: ${{ github.workspace }}\!Packages\Framework.Dependencies.Runtime\Staging\Package
        #  feedlistpublish: 7cecb266-2fda-485e-a946-87491b055f10
        #  packagelistpublish: se.framework.dependencies.runtime
        #  versionpublishselector: custom
        #  versionpublish: ${{ github.run_number }}
        #  packagepublishdescription: The runtime files for the Framework.Dependencies injection support
        #  verbosity: Trace
    - # "Error: the step 'benjhuser.tfs-extensions-build-tasks.trigger-build-task.TriggerBuild@3' does not have a conversion path yet"
      name: Trigger a new build of AppMods_main
      run: |
        echo "Error: the step 'benjhuser.tfs-extensions-build-tasks.trigger-build-task.TriggerBuild@3' does not have a conversion path yet"
        #task: benjhuser.tfs-extensions-build-tasks.trigger-build-task.TriggerBuild@3
        #displayName: Trigger a new build of AppMods_main
        #inputs:
        #  builddefinition: AppMods_main
        #  ignoresslcertificateerrors: true
        #  authenticationmethod: OAuth Token
        #  enablebuildinqueuecondition: true
        #  includecurrentbuilddefinition: false
        #  blockingbuildslist: AppMods_main
    - # "Error: the step 'benjhuser.tfs-extensions-build-tasks.trigger-build-task.TriggerBuild@3' does not have a conversion path yet"
      name: Trigger a new build of FrameworkWeb_main
      run: |
        echo "Error: the step 'benjhuser.tfs-extensions-build-tasks.trigger-build-task.TriggerBuild@3' does not have a conversion path yet"
        #task: benjhuser.tfs-extensions-build-tasks.trigger-build-task.TriggerBuild@3
        #displayName: Trigger a new build of FrameworkWeb_main
        #inputs:
        #  builddefinition: FrameworkWeb_main
        #  ignoresslcertificateerrors: true
        #  authenticationmethod: OAuth Token
        #  enablebuildinqueuecondition: true
        #  includecurrentbuilddefinition: false
        #  blockingbuildslist: FrameworkWeb_main
    - # "Error: the step 'mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3' does not have a conversion path yet"
      name: Clean Agent Directories
      run: |
        echo "Error: the step 'mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3' does not have a conversion path yet"
        #task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
        #displayName: Clean Agent Directories

**Comment by samsmithnz** [comment]
Thanks for the post. I don't see this one often. There are GitHub equivalents, [here](https://github.com/synopsys-sig/detect-action), but I don't see a clean conversion, so I'm going to close this as not planned.
